###sign up
@url_dev = http://localhost:2907

POST {{url_dev}}/v1/api/shop/signup
Content-Type: application/json

{
    "name": "adminNin",
    "email": "motlongson11@gmail.com",
    "password": "123456"
}